apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
data:
  custom_parsers.conf: |
    [PARSER]
      Name docker_no_time
      Format json
      Time_Keep Off
      Time_Key time
      Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
      Flush 1
      Daemon Off
      Log_Level info
      Parsers_File parsers.conf
      Parsers_File custom_parsers.conf
      HTTP_Server On
      HTTP_Listen 0.0.0.0
      HTTP_Port 2020

    [INPUT]
      Name        tcp
      Listen      0.0.0.0
      Port        5170
      Chunk_Size  32
      Buffer_Size 64
      Format      json

    [OUTPUT]
      Name        stdout
      Match       *