apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2020"
    prometheus.io/path: /api/v1/metrics/prometheus
spec:
  type: ClusterIP
  ports:
    - port: 2020
      targetPort: http
      protocol: TCP
      name: http
    - port: 5170
      targetPort: tcp
      protocol: TCP
      name: tcp
